# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               R + Data-Science
tagline:             'The Art and Science of Data'
description:         'Learning R and Data Science. Made by <a href="https://twitter.com/coursera_ns" target="_blank">@coursera_ns</a>.'
url:                 http://courserans.github.io
baseurl:             /
paginate:            1

# About/contact
author:
  name:              NS
  url:               https://twitter.com/coursera_ns
  email:             coursera.ns@gmail.com

# Custom vars
version:             1.0.0
